default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: Ngocnghia97
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: backbone_dev

test:
  <<: *default
  database: backbone_test